# Generated by Django 4.2.7 on 2026-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='buddy',
            field=models.CharField(blank=True, help_text='Friendly name for the user', max_length=150, null=True),
        ),
    ]
