# Generated by Django 4.2.7 on 2026-06-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_profile_picture_customuser_buddy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='buddy',
        ),
    ]
