from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain

from .llm import get_llm
from .prompts import get_rag_prompt
from .retriever import get_retriever

def get_chatbot_chain(collection_name: str, filter_dict=None):
    """
    This is the final RAG Pipeline. It glues all our previous work together!
    """
    # 1. Get the Brain (Gemini or OpenAI)
    llm = get_llm()
    
    # 2. Get the Rules (System Prompt)
    prompt = get_rag_prompt()
    
    # 3. Get the Memory Searcher (Retriever)
    retriever = get_retriever(collection_name=collection_name, filter_dict=filter_dict)
    
    # 4. Create the Document Chain
    # This chain takes the documents found by the Retriever and "stuffs" them 
    # into the {context} variable of our System Prompt.
    question_answer_chain = create_stuff_documents_chain(llm, prompt)
    
    # 5. Create the Final Retrieval Chain
    # This chain orchestrates the whole process:
    # User Input -> Retriever finds chunks -> Chunks go to Document Chain -> LLM reads it all -> LLM Answers
    rag_chain = create_retrieval_chain(retriever, question_answer_chain)
    
    return rag_chain

def ask_chatbot(collection_name: str, user_question: str, filter_dict=None) -> str:
    """
    A simple helper function to use the chatbot in your Django views.
    
    Args:
        collection_name: e.g., 'patients' or 'doctors'
        user_question: The actual question from the user.
        filter_dict: Optional filter (e.g. {"patient_id": 5})
        
    Returns:
        The text answer generated by the AI.
    """
    # Assemble the pipeline
    chain = get_chatbot_chain(collection_name, filter_dict)
    
    # Run the pipeline! We pass the user_question into the {input} variable of our prompt.
    response = chain.invoke({"input": user_question})
    
    # The response is a dictionary that includes the retrieved documents and the answer.
    # We only care about returning the final answer text.
    return response["answer"]
