# Generated by Django 4.2.7 on 2026-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_appointment_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedpatient',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
